// Code generated by mockery v2.53.6. DO NOT EDIT.

package metricmocks

import (
	context "context"
	http "net/http"

	metric "github.com/hyperledger/firefly-common/pkg/metric"
	mock "github.com/stretchr/testify/mock"

	prometheus "github.com/prometheus/client_golang/prometheus"

	promhttp "github.com/prometheus/client_golang/prometheus/promhttp"
)

// MetricsRegistry is an autogenerated mock type for the MetricsRegistry type
type MetricsRegistry struct {
	mock.Mock
}

// GetGatherer provides a mock function with no fields
func (_m *MetricsRegistry) GetGatherer() prometheus.Gatherer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGatherer")
	}

	var r0 prometheus.Gatherer
	if rf, ok := ret.Get(0).(func() prometheus.Gatherer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prometheus.Gatherer)
		}
	}

	return r0
}

// GetHTTPMetricsInstrumentationsMiddlewareForSubsystem provides a mock function with given fields: ctx, subsystem
func (_m *MetricsRegistry) GetHTTPMetricsInstrumentationsMiddlewareForSubsystem(ctx context.Context, subsystem string) (func(http.Handler) http.Handler, error) {
	ret := _m.Called(ctx, subsystem)

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPMetricsInstrumentationsMiddlewareForSubsystem")
	}

	var r0 func(http.Handler) http.Handler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (func(http.Handler) http.Handler, error)); ok {
		return rf(ctx, subsystem)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) func(http.Handler) http.Handler); ok {
		r0 = rf(ctx, subsystem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subsystem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPHandler provides a mock function with given fields: ctx, handlerOpts
func (_m *MetricsRegistry) HTTPHandler(ctx context.Context, handlerOpts promhttp.HandlerOpts) (http.Handler, error) {
	ret := _m.Called(ctx, handlerOpts)

	if len(ret) == 0 {
		panic("no return value specified for HTTPHandler")
	}

	var r0 http.Handler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, promhttp.HandlerOpts) (http.Handler, error)); ok {
		return rf(ctx, handlerOpts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, promhttp.HandlerOpts) http.Handler); ok {
		r0 = rf(ctx, handlerOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, promhttp.HandlerOpts) error); ok {
		r1 = rf(ctx, handlerOpts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MustRegisterCollector provides a mock function with given fields: collector
func (_m *MetricsRegistry) MustRegisterCollector(collector prometheus.Collector) {
	_m.Called(collector)
}

// NewHTTPMetricsInstrumentationsForSubsystem provides a mock function with given fields: ctx, subsystem, useRouteTemplate, reqDurationBuckets, labels
func (_m *MetricsRegistry) NewHTTPMetricsInstrumentationsForSubsystem(ctx context.Context, subsystem string, useRouteTemplate bool, reqDurationBuckets []float64, labels map[string]string) error {
	ret := _m.Called(ctx, subsystem, useRouteTemplate, reqDurationBuckets, labels)

	if len(ret) == 0 {
		panic("no return value specified for NewHTTPMetricsInstrumentationsForSubsystem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, []float64, map[string]string) error); ok {
		r0 = rf(ctx, subsystem, useRouteTemplate, reqDurationBuckets, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricsManagerForSubsystem provides a mock function with given fields: ctx, subsystem
func (_m *MetricsRegistry) NewMetricsManagerForSubsystem(ctx context.Context, subsystem string) (metric.MetricsManager, error) {
	ret := _m.Called(ctx, subsystem)

	if len(ret) == 0 {
		panic("no return value specified for NewMetricsManagerForSubsystem")
	}

	var r0 metric.MetricsManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (metric.MetricsManager, error)); ok {
		return rf(ctx, subsystem)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) metric.MetricsManager); ok {
		r0 = rf(ctx, subsystem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metric.MetricsManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subsystem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetricsRegistry creates a new instance of MetricsRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRegistry {
	mock := &MetricsRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
